export const MARQUES_VOITURE = [
  "Alfa Romeo", "Aston Martin", "Audi", "BMW", "Bentley", "Bugatti",
  "Cadillac", "Chevrolet", "Chrysler", "Citroën", "Dacia", "DS Automobiles",
  "Ferrari", "Fiat", "Ford", "Honda", "Hyundai", "Infiniti", "Jaguar",
  "Jeep", "Kia", "Lamborghini", "Land Rover", "Lexus", "Maserati",
  "Mazda", "McLaren", "Mercedes-Benz", "MG", "Mini", "Mitsubishi",
  "Nissan", "Opel", "Peugeot", "Porsche", "Renault", "Rolls-Royce",
  "SEAT", "Skoda", "Smart", "Subaru", "Suzuki", "Tesla", "Toyota",
  "Volkswagen", "Volvo", "BYD", "Lynk & Co", "Polestar", "Genesis",
].sort();

export const MODELES_PAR_MARQUE: Record<string, string[]> = {
  "Peugeot": ["106", "107", "108", "205", "206", "207", "208", "3008", "301", "306", "307", "308", "4008", "407", "408", "5008", "508", "Expert", "Partner", "Rifter"],
  "Renault": ["Captur", "Clio", "Espace", "Express", "Fluence", "Kadjar", "Kangoo", "Koleos", "Laguna", "Master", "Megane", "Modus", "Sandero", "Scenic", "Symbol", "Trafic", "Twingo", "Zoe"],
  "Citroën": ["Berlingo", "C1", "C2", "C3", "C3 Aircross", "C4", "C4 Cactus", "C4 Picasso", "C5", "C5 Aircross", "C5 X", "C6", "DS3", "DS4", "DS5", "Jumpy", "Nemo", "Picasso"],
  "Volkswagen": ["Arteon", "Caddy", "Golf", "ID.3", "ID.4", "ID.5", "Passat", "Polo", "Sharan", "T-Cross", "T-Roc", "Taigo", "Tiguan", "Touareg", "Touran", "Up!"],
  "BMW": ["Série 1", "Série 2", "Série 3", "Série 4", "Série 5", "Série 6", "Série 7", "Série 8", "X1", "X2", "X3", "X4", "X5", "X6", "X7", "iX", "i3", "i4", "i5", "i7"],
  "Mercedes-Benz": ["Classe A", "Classe B", "Classe C", "Classe E", "Classe G", "Classe S", "CLA", "CLE", "EQA", "EQB", "EQC", "EQE", "EQS", "GLA", "GLB", "GLC", "GLE", "GLS", "Vito"],
  "Audi": ["A1", "A2", "A3", "A4", "A5", "A6", "A7", "A8", "E-Tron", "Q2", "Q3", "Q4 E-Tron", "Q5", "Q7", "Q8", "R8", "RS3", "RS6", "TT"],
  "Toyota": ["Aygo", "C-HR", "Camry", "Corolla", "Hilux", "Land Cruiser", "Prius", "ProAce", "RAV4", "Supra", "Verso", "Yaris", "bZ4X"],
  "Ford": ["B-Max", "C-Max", "EcoSport", "Edge", "Explorer", "Fiesta", "Focus", "Galaxy", "Kuga", "Mondeo", "Mustang", "Puma", "Ranger", "S-Max", "Transit"],
  "Dacia": ["Dokker", "Duster", "Jogger", "Lodgy", "Logan", "Sandero", "Sandero Stepway", "Spring"],
  "Honda": ["Accord", "Civic", "CR-V", "HR-V", "Jazz", "NSX", "Type R"],
  "Hyundai": ["Bayon", "i10", "i20", "i30", "i40", "IONIQ", "IONIQ 5", "IONIQ 6", "Kona", "Santa Fe", "Tucson"],
  "Kia": ["Ceed", "EV6", "Niro", "Picanto", "ProCeed", "Sorento", "Soul", "Sportage", "Stinger", "Stonic", "XCeed"],
  "Nissan": ["Ariya", "Juke", "Leaf", "Micra", "Navara", "Qashqai", "X-Trail"],
  "Fiat": ["500", "500L", "500X", "Bravo", "Doblo", "Ducato", "Grande Punto", "Panda", "Punto", "Tipo"],
  "Opel": ["Adam", "Astra", "Corsa", "Crossland", "Grandland", "Insignia", "Meriva", "Mokka", "Zafira"],
  "Skoda": ["Citigo", "Fabia", "Kamiq", "Karoq", "Kodiaq", "Octavia", "Scala", "Superb", "Yeti"],
  "SEAT": ["Arona", "Ateca", "Ibiza", "Leon", "Mii", "Tarraco", "Alhambra"],
  "Tesla": ["Model 3", "Model S", "Model X", "Model Y", "Cybertruck"],
  "DS Automobiles": ["DS 3", "DS 4", "DS 5", "DS 7", "DS 9"],
  "Alfa Romeo": ["147", "156", "159", "4C", "Brera", "Giulia", "Giulietta", "GTV", "MiTo", "Spider", "Stelvio", "Tonale"],
  "Aston Martin": ["DB11", "DB12", "DBS Superleggera", "DBX", "Rapide", "Vantage"],
  "Bentley": ["Bentayga", "Continental GT", "Flying Spur", "Mulsanne"],
  "Bugatti": ["Chiron", "Divo", "Veyron"],
  "BYD": ["Atto 2", "Atto 3", "Dolphin", "Han", "Seal", "Sealion 6", "Tang"],
  "Cadillac": ["CT4", "CT5", "Escalade", "XT4", "XT5", "XT6"],
  "Chevrolet": ["Camaro", "Corvette", "Equinox", "Silverado", "Suburban", "Tahoe", "Trailblazer"],
  "Chrysler": ["300", "Pacifica", "Voyager"],
  "Ferrari": ["296 GTB", "488 GTB", "812 Superfast", "California T", "F8 Tributo", "Portofino", "Purosangue", "Roma", "SF90 Stradale"],
  "Genesis": ["G70", "G80", "G90", "GV60", "GV70", "GV80"],
  "Infiniti": ["Q30", "Q50", "Q60", "QX30", "QX50", "QX55", "QX60", "QX80"],
  "Jaguar": ["E-Pace", "F-Pace", "F-Type", "I-Pace", "XE", "XF", "XJ"],
  "Jeep": ["Avenger", "Cherokee", "Commander", "Compass", "Gladiator", "Grand Cherokee", "Renegade", "Wrangler"],
  "Lamborghini": ["Huracán", "Revuelto", "Urus"],
  "Land Rover": ["Defender", "Discovery", "Discovery Sport", "Freelander", "Range Rover", "Range Rover Evoque", "Range Rover Sport", "Range Rover Velar"],
  "Lexus": ["CT", "ES", "IS", "LC", "LBX", "LS", "LX", "NX", "RX", "UX"],
  "Lynk & Co": ["01", "02", "03", "05"],
  "Maserati": ["Ghibli", "GranTurismo", "Grecale", "Levante", "MC20", "Quattroporte"],
  "Mazda": ["2", "3", "6", "CX-3", "CX-30", "CX-5", "CX-60", "CX-80", "MX-5", "MX-30"],
  "McLaren": ["540C", "570S", "600LT", "720S", "Artura", "GT"],
  "MG": ["3", "4", "5", "HS", "Marvel R", "ZS", "ZS EV"],
  "Mini": ["Cabrio", "Clubman", "Cooper", "Cooper S", "Countryman", "JCW", "Paceman"],
  "Mitsubishi": ["ASX", "Eclipse Cross", "L200", "Outlander", "Space Star"],
  "Polestar": ["1", "2", "3", "4"],
  "Porsche": ["718 Boxster", "718 Cayman", "911", "Cayenne", "Macan", "Panamera", "Taycan"],
  "Rolls-Royce": ["Cullinan", "Dawn", "Ghost", "Phantom", "Spectre", "Wraith"],
  "Smart": ["#1", "#3", "EQ forfour", "EQ fortwo", "fortwo"],
  "Subaru": ["BRZ", "Forester", "Impreza", "Legacy", "Levorg", "Outback", "WRX", "XV"],
  "Suzuki": ["Baleno", "Celerio", "Ignis", "Jimny", "S-Cross", "Swace", "Swift", "Vitara"],
  "Volvo": ["C30", "C40", "S60", "S90", "V40", "V60", "V90", "XC40", "XC60", "XC90"],
};

export function getModelesForMarque(marque: string): string[] {
  return MODELES_PAR_MARQUE[marque] ?? [];
}

export const FINITIONS_PAR_MODELE: Record<string, string[]> = {
  // Peugeot
  "Peugeot|106": ["Accent", "XN", "XR", "XS", "XT", "S16", "Rallye"],
  "Peugeot|205": ["GL", "GR", "GT", "GTI", "Cabriolet"],
  "Peugeot|206": ["Trendy", "XR", "XS", "XT", "SR", "S16", "GTI", "CC", "SW"],
  "Peugeot|207": ["Access", "Urban", "Trendy", "Sport", "Sportium", "Outdoor", "SW", "CC"],
  "Peugeot|208": ["Active", "Active Pack", "Allure", "Allure Pack", "GT", "GT Pack", "e-208"],
  "Peugeot|2008": ["Active", "Active Pack", "Allure", "Allure Pack", "GT", "GT Pack", "e-2008"],
  "Peugeot|301": ["Access", "Active", "Allure", "Style"],
  "Peugeot|306": ["XN", "XR", "XT", "XS", "SR", "S16", "Cabriolet", "Break"],
  "Peugeot|307": ["Presence", "Confort", "Pack", "Premium", "SW", "CC"],
  "Peugeot|308": ["Active Pack", "Allure", "Allure Pack", "GT", "GT Pack", "GT Premium"],
  "Peugeot|3008": ["Active Pack", "Allure", "Allure Pack", "GT", "GT Pack", "GT Premium"],
  "Peugeot|4008": ["Access", "Active", "Allure", "GT Line", "Outdoor"],
  "Peugeot|406": ["SL", "SR", "ST", "SV", "SE", "S16", "Pack", "Break", "Coupé"],
  "Peugeot|407": ["Confort", "Executive", "Premium", "Sport", "SW", "GT"],
  "Peugeot|408": ["Active Pack", "Allure", "Allure Pack", "GT", "GT Premium"],
  "Peugeot|5008": ["Active Pack", "Allure", "Allure Pack", "GT", "GT Pack"],
  "Peugeot|508": ["Active Pack", "Allure", "Allure Pack", "GT", "GT Pack", "SW"],
  "Peugeot|108": ["Like", "Active", "Allure", "Roland Garros"],
  "Peugeot|107": ["Urban", "Trendy", "Sport", "Sportium"],
  "Peugeot|Partner": ["Base", "Active", "Allure", "Tepee", "Tepee Active", "Tepee Allure"],
  "Peugeot|Rifter": ["Active", "Active Pack", "Allure", "Allure Pack", "GT", "Long"],
  "Peugeot|Expert": ["Premium", "Compact", "Standard", "Long", "Traveller"],
  // Renault
  "Renault|Clio": ["Life", "Zen", "Business", "Intens", "RS Line", "E-Tech"],
  "Renault|Megane": ["Life", "Zen", "Business", "Intens", "RS Line", "Edition One"],
  "Renault|Captur": ["Life", "Zen", "Business", "Intens", "RS Line", "Edition One"],
  "Renault|Kadjar": ["Life", "Zen", "Business", "Intens", "Bose"],
  "Renault|Scenic": ["Life", "Zen", "Business", "Intens", "Bose"],
  "Renault|Koleos": ["Life", "Zen", "Intens", "Initiale Paris"],
  "Renault|Twingo": ["Life", "Zen", "Intens", "Edition One"],
  "Renault|Zoe": ["Life", "Zen", "Intens", "Edition One", "R135"],
  "Renault|Espace": ["Zen", "Intens", "Initiale Paris"],
  "Renault|Kangoo": ["Confort", "Business", "Intens"],
  "Renault|Laguna": ["Expression", "Dynamique", "Privilège", "GT", "Estate", "Coupé"],
  "Renault|Fluence": ["Expression", "Dynamique", "Privilège", "GT Line"],
  "Renault|Modus": ["Authentique", "Expression", "Dynamique", "Privilège"],
  "Renault|Symbol": ["Authentique", "Expression", "Privilège"],
  "Renault|Trafic": ["Combi", "Fourgon", "Combi L1", "Combi L2", "SpaceClass"],
  "Renault|Master": ["L1H1", "L2H2", "L3H3", "Propulsion", "Grand Confort"],
  "Renault|Express": ["Confort", "Base"],
  "Renault|Sandero": ["Access", "Authentique", "Expression", "Stepway"],
  // Citroën
  "Citroën|C1": ["Feel", "Feel Edition", "Shine"],
  "Citroën|C2": ["SX", "VTR", "VTS"],
  "Citroën|C3": ["Feel", "Feel Pack", "Shine", "Shine Pack", "You!", "MAX"],
  "Citroën|C3 Aircross": ["Feel", "Feel Pack", "Shine", "Shine Pack", "MAX"],
  "Citroën|C4": ["Feel", "Feel Pack", "Shine", "Shine Pack", "MAX"],
  "Citroën|C4 Cactus": ["Feel", "Feel Pack", "Shine", "Shine Pack"],
  "Citroën|C4 Picasso": ["Attraction", "Séduction", "Exclusive", "Intensive"],
  "Citroën|C5": ["Confort", "Exclusive", "Dynamique", "Séduction"],
  "Citroën|C5 Aircross": ["Feel", "Feel Pack", "Shine", "Shine Pack", "MAX"],
  "Citroën|C5 X": ["Feel Pack", "Shine", "Shine Pack", "MAX"],
  "Citroën|C6": ["Exclusive", "Dynamique"],
  "Citroën|Berlingo": ["Base", "Feel", "Feel Pack", "Shine", "M", "XL"],
  "Citroën|DS3": ["Chic", "So Chic", "Sport Chic", "Ultra Prestige"],
  "Citroën|DS4": ["Chic", "So Chic", "Sport Chic", "Ultra Prestige"],
  "Citroën|DS5": ["Chic", "So Chic", "Sport Chic", "Ultra Prestige", "Hybrid4"],
  "Citroën|Jumpy": ["Base", "Business", "Business+", "XL"],
  "Citroën|Nemo": ["Base", "Business"],
  "Citroën|Picasso": ["Attraction", "Séduction", "Exclusive"],
  // Volkswagen
  "Volkswagen|Golf": ["Life", "Style", "R-Line", "GTI", "GTI Performance", "R", "GTE"],
  "Volkswagen|Polo": ["Life", "Style", "R-Line", "GTI"],
  "Volkswagen|Tiguan": ["Life", "Elegance", "R-Line", "R"],
  "Volkswagen|Taigo": ["Life", "Style", "R-Line"],
  "Volkswagen|T-Roc": ["Life", "Style", "R-Line", "Cabriolet"],
  "Volkswagen|T-Cross": ["Life", "Style", "R-Line"],
  "Volkswagen|Passat": ["Life", "Elegance", "R-Line", "GTE"],
  "Volkswagen|Touareg": ["Life", "Elegance", "R-Line", "R"],
  "Volkswagen|Touran": ["Life", "Elegance", "R-Line"],
  "Volkswagen|Arteon": ["Elegance", "R-Line", "R-Line Shooting Brake"],
  "Volkswagen|Caddy": ["Base", "Life", "Commerce", "Maxi"],
  "Volkswagen|Sharan": ["Comfortline", "Highline", "Allstar"],
  "Volkswagen|Up!": ["Move Up!", "Take Up!", "High Up!"],
  "Volkswagen|ID.3": ["Life", "Pro", "Pro S", "Tour"],
  "Volkswagen|ID.4": ["Life", "Pro", "Pro S", "GTX"],
  "Volkswagen|ID.5": ["Pro", "Pro S", "GTX"],
  // BMW
  "BMW|Série 1": ["Sport Line", "Lounge", "M Sport", "M Sport Pro"],
  "BMW|Série 2": ["Sport Line", "Lounge", "M Sport", "M235i", "M240i"],
  "BMW|Série 3": ["Lounge", "Business", "Business Design", "M Sport", "M Sport Pro"],
  "BMW|Série 4": ["Lounge", "Business", "M Sport", "M440i", "M4"],
  "BMW|Série 5": ["Lounge", "Business", "Business Design", "M Sport", "M Sport Pro"],
  "BMW|Série 6": ["Gran Coupé Lounge", "Gran Coupé M Sport", "Gran Turismo Lounge", "M6"],
  "BMW|Série 7": ["Lounge", "M Sport", "M760e", "Individual"],
  "BMW|Série 8": ["Coupé M Sport", "Cabriolet M Sport", "Gran Coupé M Sport", "M8"],
  "BMW|X1": ["xLine", "Luxury", "M Sport"],
  "BMW|X2": ["xLine", "Luxury", "M Sport", "M35i"],
  "BMW|X3": ["xLine", "Luxury", "M Sport", "M40i"],
  "BMW|X4": ["xLine", "Luxury", "M Sport", "M40i"],
  "BMW|X5": ["xLine", "Luxury", "M Sport", "M50i"],
  "BMW|X6": ["xLine", "M Sport", "M60i"],
  "BMW|X7": ["xLine", "Luxury", "M Sport", "M60i"],
  "BMW|iX": ["xDrive40", "xDrive50", "M60"],
  "BMW|i3": ["Base", "s"],
  "BMW|i4": ["eDrive35", "eDrive40", "M50"],
  "BMW|i5": ["eDrive40", "M60"],
  "BMW|i7": ["eDrive60", "M70"],
  // Mercedes-Benz
  "Mercedes-Benz|Classe A": ["Progressive", "AMG Line", "AMG Line Premium", "Edition 1"],
  "Mercedes-Benz|Classe B": ["Progressive", "AMG Line", "AMG Line Premium"],
  "Mercedes-Benz|Classe C": ["Avantgarde", "AMG Line", "AMG Line Premium", "C 63"],
  "Mercedes-Benz|Classe E": ["Avantgarde", "AMG Line", "AMG Line Premium", "E 63"],
  "Mercedes-Benz|Classe G": ["AMG Line", "G 63 AMG"],
  "Mercedes-Benz|Classe S": ["Progressive", "AMG Line", "AMG Line Premium", "Maybach"],
  "Mercedes-Benz|CLA": ["Progressive", "AMG Line", "AMG Line Premium", "CLA 45"],
  "Mercedes-Benz|CLE": ["Progressive", "AMG Line", "CLE 53"],
  "Mercedes-Benz|GLA": ["Progressive", "AMG Line", "AMG Line Premium"],
  "Mercedes-Benz|GLB": ["Progressive", "AMG Line", "AMG Line Premium"],
  "Mercedes-Benz|GLC": ["Progressive", "AMG Line", "AMG Line Premium", "GLC 63"],
  "Mercedes-Benz|GLE": ["Progressive", "AMG Line", "AMG Line Premium", "GLE 63"],
  "Mercedes-Benz|GLS": ["Progressive", "AMG Line", "AMG Line Premium", "GLS 63"],
  "Mercedes-Benz|EQA": ["Progressive", "AMG Line", "AMG Line Premium"],
  "Mercedes-Benz|EQB": ["Progressive", "AMG Line", "AMG Line Premium"],
  "Mercedes-Benz|EQC": ["Progressive", "AMG Line", "Edition 1886"],
  "Mercedes-Benz|EQE": ["Progressive", "AMG Line", "AMG Line Premium"],
  "Mercedes-Benz|EQS": ["Progressive", "AMG Line", "AMG Line Premium"],
  "Mercedes-Benz|Vito": ["Base", "Pro", "Tourer", "Tourer Pro"],
  // Audi
  "Audi|A1": ["30 TFSI", "35 TFSI", "S Line", "S1"],
  "Audi|A2": ["1.4", "1.6 FSI", "1.4 TDI"],
  "Audi|A3": ["Business", "Design", "S Line", "S3", "RS3"],
  "Audi|A4": ["Business", "Design", "S Line", "S4", "RS4"],
  "Audi|A5": ["Business", "Design", "S Line", "S5", "RS5"],
  "Audi|A6": ["Business", "Design", "S Line", "S6", "RS6"],
  "Audi|A7": ["Business", "Design", "S Line", "S7", "RS7"],
  "Audi|A8": ["Business", "Design", "S Line", "S8", "Individual"],
  "Audi|Q2": ["Business", "Design", "S Line"],
  "Audi|Q3": ["Business", "Design", "S Line", "RS Q3"],
  "Audi|Q4 E-Tron": ["Business", "Design", "S Line"],
  "Audi|Q5": ["Business", "Design", "S Line", "SQ5", "RS Q5"],
  "Audi|Q7": ["Business", "Design", "S Line", "SQ7"],
  "Audi|Q8": ["Business", "Design", "S Line", "SQ8", "RS Q8"],
  "Audi|E-Tron": ["Business", "Design", "S Line", "S"],
  "Audi|R8": ["V10", "V10 Performance", "Spyder"],
  "Audi|RS3": ["Base", "Performance"],
  "Audi|RS6": ["Base", "Performance", "Carbon Black"],
  "Audi|TT": ["40 TFSI", "45 TFSI", "TTS", "TTS Roadster", "RS"],
  // Toyota
  "Toyota|Aygo": ["X-Play", "X-Trend", "X-Cite", "X-Style"],
  "Toyota|Yaris": ["Dynamic", "Active", "Collection", "GR Sport", "Première"],
  "Toyota|Corolla": ["Dynamic", "Active", "Collection", "GR Sport"],
  "Toyota|C-HR": ["Dynamic", "Active", "Collection", "GR Sport"],
  "Toyota|Camry": ["Dynamic", "Active", "Collection", "Executive"],
  "Toyota|RAV4": ["Dynamic", "Active", "Collection", "AWD-i", "Plug-in"],
  "Toyota|Prius": ["Dynamic", "Active", "Collection", "Rechargeable"],
  "Toyota|bZ4X": ["Dynamic", "Active", "Collection"],
  "Toyota|Land Cruiser": ["TX", "VX", "Invincible", "Invincible+", "GR Sport"],
  "Toyota|Hilux": ["Active", "Design", "Lounge", "Invincible"],
  "Toyota|ProAce": ["Base", "Combi", "Verso", "Electric"],
  "Toyota|Supra": ["Base", "GR Supra", "GR Supra Track Edition"],
  "Toyota|Verso": ["Active", "Premium", "Luna"],
  // Ford
  "Ford|B-Max": ["Trend", "Titanium", "Sport"],
  "Ford|C-Max": ["Trend", "Cool & Connect", "Titanium", "ST-Line"],
  "Ford|EcoSport": ["Trend", "Titanium", "ST-Line", "Active"],
  "Ford|Edge": ["Titanium", "ST-Line", "Vignale"],
  "Ford|Explorer": ["ST-Line", "Platinum", "Plug-In Hybrid"],
  "Ford|Fiesta": ["Trend", "Cool & Connect", "Titanium", "ST-Line", "ST-Line X", "Vignale", "Active", "ST"],
  "Ford|Focus": ["Trend", "Cool & Connect", "Titanium", "ST-Line", "ST-Line X", "Vignale", "Active", "ST"],
  "Ford|Galaxy": ["Trend", "Titanium", "ST-Line", "Vignale"],
  "Ford|Kuga": ["Trend", "Cool & Connect", "Titanium", "ST-Line", "ST-Line X", "Vignale", "Plug-In Hybrid"],
  "Ford|Mondeo": ["Trend", "Titanium", "ST-Line", "ST-Line X", "Vignale"],
  "Ford|Mustang": ["EcoBoost", "GT", "Mach-E", "Dark Horse", "Shelby GT500"],
  "Ford|Puma": ["Trend", "Cool & Connect", "Titanium", "ST-Line", "ST-Line X", "Vignale", "ST"],
  "Ford|Ranger": ["Regular Cab", "Super Cab", "Double Cab XL", "Wildtrak", "Raptor"],
  "Ford|S-Max": ["Trend", "Titanium", "ST-Line", "Vignale"],
  "Ford|Transit": ["Base", "Trend", "Limited", "Custom", "Courier"],
  // Dacia
  "Dacia|Dokker": ["Access", "Essential", "Stepway"],
  "Dacia|Duster": ["Essential", "Expression", "Extreme", "Journey", "4x4"],
  "Dacia|Jogger": ["Essential", "Expression", "Extreme", "Hybrid 140"],
  "Dacia|Lodgy": ["Access", "Ambiance", "Stepway", "Prestige"],
  "Dacia|Logan": ["Access", "Essential", "Confort", "Prestige"],
  "Dacia|Sandero": ["Essential", "Expression", "Extreme", "Stepway Essential", "Stepway Expression", "Stepway Extreme"],
  "Dacia|Sandero Stepway": ["Essential", "Expression", "Extreme"],
  "Dacia|Spring": ["Essential", "Expression", "Extreme"],
  // Skoda
  "Skoda|Citigo": ["Active", "Ambition", "Style"],
  "Skoda|Fabia": ["Active", "Ambition", "Style", "Monte Carlo"],
  "Skoda|Kamiq": ["Active", "Ambition", "Style", "Monte Carlo"],
  "Skoda|Karoq": ["Active", "Ambition", "Style", "Sportline"],
  "Skoda|Kodiaq": ["Active", "Ambition", "Style", "Sportline", "RS"],
  "Skoda|Octavia": ["Active", "Ambition", "Style", "Sportline", "RS"],
  "Skoda|Scala": ["Active", "Ambition", "Style", "Monte Carlo"],
  "Skoda|Superb": ["Active", "Ambition", "Style", "Laurin & Klement"],
  "Skoda|Yeti": ["Active", "Ambition", "Style", "Outdoor"],
  // SEAT
  "SEAT|Alhambra": ["Reference", "Style", "Xcellence"],
  "SEAT|Arona": ["Reference", "Style", "FR", "Xcellence"],
  "SEAT|Ateca": ["Reference", "Style", "FR", "Xcellence", "CUPRA"],
  "SEAT|Ibiza": ["Reference", "Style", "FR", "Xcellence"],
  "SEAT|Leon": ["Reference", "Style", "FR", "Xcellence", "FR Sport", "CUPRA"],
  "SEAT|Mii": ["Base", "Style", "FR Line"],
  "SEAT|Tarraco": ["Reference", "Style", "FR", "Xcellence"],
  // Opel
  "Opel|Adam": ["Jam", "Glam", "Slam", "Rocks"],
  "Opel|Astra": ["Edition", "GS", "GS Line", "Ultimate", "Electric"],
  "Opel|Corsa": ["Edition", "GS", "GS Line", "Ultimate", "Electric"],
  "Opel|Crossland": ["Edition", "GS", "GS Line", "Ultimate"],
  "Opel|Grandland": ["Edition", "GS", "GS Line", "Ultimate", "Plug-in Hybrid"],
  "Opel|Insignia": ["Edition", "Elegance", "GS Line", "Ultimate"],
  "Opel|Meriva": ["Base", "Active", "Cosmo"],
  "Opel|Mokka": ["Edition", "GS", "GS Line", "Ultimate", "Electric"],
  "Opel|Zafira": ["Base", "Active", "Cosmo", "OPC"],
  // DS Automobiles
  "DS Automobiles|DS 3": ["Bastille", "Performance Line", "Opéra", "Rivoli", "La Première"],
  "DS Automobiles|DS 4": ["Bastille", "Performance Line", "Opéra", "Rivoli", "La Première"],
  "DS Automobiles|DS 5": ["Chic", "So Chic", "Sport Chic", "Ultra Prestige", "Hybrid4"],
  "DS Automobiles|DS 7": ["Bastille", "Performance Line", "Opéra", "Rivoli", "Grand Chic", "La Première"],
  "DS Automobiles|DS 9": ["Bastille", "Performance Line", "Opéra", "Rivoli", "La Première"],
  // Kia
  "Kia|Ceed": ["Active", "GT-Line", "GT-Line Premium", "GT"],
  "Kia|EV6": ["Air", "Wind", "Earth", "GT-Line", "GT"],
  "Kia|Niro": ["Active", "GT-Line", "GT-Line Premium"],
  "Kia|Picanto": ["Active", "GT-Line", "GT-Line Premium"],
  "Kia|ProCeed": ["GT-Line", "GT-Line Premium", "GT"],
  "Kia|Sorento": ["Active", "GT-Line", "GT-Line Premium"],
  "Kia|Soul": ["Active", "GT-Line", "GT-Line Premium"],
  "Kia|Sportage": ["Active", "GT-Line", "GT-Line Premium", "GT-Line Executive"],
  "Kia|Stinger": ["GT-Line", "GT"],
  "Kia|Stonic": ["Active", "GT-Line", "GT-Line Premium"],
  "Kia|XCeed": ["Active", "GT-Line", "GT-Line Premium"],
  // Hyundai
  "Hyundai|Bayon": ["Intuitive", "Creative", "N Line"],
  "Hyundai|i10": ["Intuitive", "Creative", "N Line"],
  "Hyundai|i20": ["Intuitive", "Creative", "N Line", "N"],
  "Hyundai|i30": ["Intuitive", "Creative", "N Line", "N"],
  "Hyundai|i40": ["Comfort", "Business", "Style"],
  "Hyundai|IONIQ": ["Comfort", "Creative", "Intuitive", "Premium"],
  "Hyundai|IONIQ 5": ["Intuitive", "Creative", "Lounge", "N"],
  "Hyundai|IONIQ 6": ["Intuitive", "Creative", "Lounge"],
  "Hyundai|Kona": ["Intuitive", "Creative", "N Line", "N", "Electric"],
  "Hyundai|Santa Fe": ["Creative", "Executive", "N Line"],
  "Hyundai|Tucson": ["Creative", "Htrac", "N Line", "N Line Premium", "Plug-in"],
  // Nissan
  "Nissan|Ariya": ["Engage", "Advance", "Evolve", "Evolve+"],
  "Nissan|Juke": ["Visia", "Acenta", "N-Connecta", "Tekna", "Tekna+", "N-Sport"],
  "Nissan|Leaf": ["Acenta", "N-Connecta", "Tekna", "Tekna+"],
  "Nissan|Micra": ["Visia", "Acenta", "N-Connecta", "Tekna"],
  "Nissan|Navara": ["Visia", "Acenta", "N-Guard", "Tekna"],
  "Nissan|Qashqai": ["Visia", "Acenta", "N-Connecta", "Tekna", "Tekna+", "N-Sport"],
  "Nissan|X-Trail": ["Acenta", "N-Connecta", "Tekna", "Tekna+"],
  // Fiat
  "Fiat|500": ["Pop", "Mirror", "Dolcevita", "Sport", "La Prima", "Electric"],
  "Fiat|500L": ["Pop", "Mirror", "Cross", "Wagon"],
  "Fiat|500X": ["Pop", "Mirror", "Cross", "Sport", "Dolcevita"],
  "Fiat|Bravo": ["Active", "Dynamic", "Sport"],
  "Fiat|Doblo": ["Pop", "Active", "Emotion", "Adventure"],
  "Fiat|Ducato": ["Base", "Plus", "Max", "Electric"],
  "Fiat|Grande Punto": ["Active", "Dynamic", "Eleganza", "Sport"],
  "Fiat|Panda": ["Pop", "Easy", "Cross", "City Life", "Trussardi"],
  "Fiat|Punto": ["Active", "Pop", "Dynamic", "Sport", "Sporting"],
  "Fiat|Tipo": ["Pop", "Mirror", "City Life", "Cross", "Sport"],
  // Honda
  "Honda|Accord": ["Comfort", "Executive", "Type S"],
  "Honda|Civic": ["Elegance", "Sport", "Advance", "Advance Style", "Type R"],
  "Honda|CR-V": ["Elegance", "Sport", "Advance", "Advance Style"],
  "Honda|HR-V": ["Elegance", "Sport", "Advance"],
  "Honda|Jazz": ["Elegance", "Crosstar", "Advance"],
  "Honda|NSX": ["Base"],
  "Honda|Type R": ["FK8", "FL5"],
  // Mazda
  "Mazda|2": ["Elegance", "Exclusive-Line", "Homura", "Takumi"],
  "Mazda|3": ["Elegance", "Exclusive-Line", "Homura", "Takumi"],
  "Mazda|6": ["Elegance", "Exclusive-Line", "Homura", "Takumi"],
  "Mazda|CX-3": ["Elegance", "Exclusive-Line", "Homura", "Takumi"],
  "Mazda|CX-30": ["Elegance", "Exclusive-Line", "Homura", "Takumi"],
  "Mazda|CX-5": ["Elegance", "Exclusive-Line", "Homura", "Takumi"],
  "Mazda|CX-60": ["Elegance", "Exclusive-Line", "Homura", "Takumi"],
  "Mazda|MX-5": ["Elegance", "Exclusive-Line", "Homura", "Takumi"],
  // Mini
  "Mini|Cooper": ["One", "Cooper", "Cooper S", "JCW", "Cooper SE"],
  "Mini|Countryman": ["One", "Cooper", "Cooper S", "JCW", "Cooper SE"],
  "Mini|Clubman": ["One", "Cooper", "Cooper S", "JCW"],
  "Mini|Cabrio": ["One", "Cooper", "Cooper S", "JCW"],
  // Tesla
  "Tesla|Model 3": ["Standard Range", "Long Range", "Performance"],
  "Tesla|Model Y": ["Standard Range", "Long Range", "Performance"],
  "Tesla|Model S": ["Dual Motor", "Plaid"],
  "Tesla|Model X": ["Dual Motor", "Plaid"],
  "Tesla|Cybertruck": ["Rear-Wheel Drive", "All-Wheel Drive", "Cyberbeast"],
  // Alfa Romeo
  "Alfa Romeo|147": ["Twin Spark", "Progression", "Distinctive", "GTA", "Sportwagon"],
  "Alfa Romeo|156": ["Twin Spark", "V6", "Distinctive", "GTA", "Sportwagon"],
  "Alfa Romeo|159": ["Progression", "Distinctive", "Sportwagon", "Ti"],
  "Alfa Romeo|4C": ["Base", "Spider"],
  "Alfa Romeo|Brera": ["2.2 JTS", "2.4 JTDm", "3.2 JTS V6"],
  "Alfa Romeo|Giulia": ["Super", "Sprint", "Veloce", "Quadrifoglio"],
  "Alfa Romeo|Giulietta": ["Sprint", "Super", "Veloce", "QV"],
  "Alfa Romeo|GTV": ["1.8 Twin Spark", "2.0 JTS", "3.0 V6 24V"],
  "Alfa Romeo|MiTo": ["Sprint", "Super", "Veloce", "QV"],
  "Alfa Romeo|Spider": ["1.8 Twin Spark", "2.0 JTS", "3.2 V6"],
  "Alfa Romeo|Stelvio": ["Super", "Sprint", "Veloce", "Quadrifoglio"],
  "Alfa Romeo|Tonale": ["Sprint", "Super", "Veloce", "Edizione Speciale"],
  // Jeep
  "Jeep|Renegade": ["Sport", "Longitude", "Limited", "Trailhawk", "S"],
  "Jeep|Compass": ["Sport", "Longitude", "Limited", "Trailhawk", "S", "Plug-in Hybrid"],
  "Jeep|Cherokee": ["Sport", "Longitude", "Limited", "Trailhawk", "Overland"],
  "Jeep|Grand Cherokee": ["Laredo", "Limited", "Overland", "Summit", "Trailhawk"],
  "Jeep|Wrangler": ["Sport", "Sahara", "Rubicon", "4xe"],
  "Jeep|Avenger": ["Longitude", "Altitude", "Summit", "Electric"],
  // Land Rover
  "Land Rover|Range Rover": ["SE", "HSE", "Autobiography", "SV"],
  "Land Rover|Range Rover Sport": ["SE", "HSE", "Dynamic SE", "Dynamic HSE", "Autobiography"],
  "Land Rover|Range Rover Evoque": ["S", "SE", "R-Dynamic S", "R-Dynamic SE", "R-Dynamic HSE"],
  "Land Rover|Range Rover Velar": ["S", "SE", "R-Dynamic S", "R-Dynamic SE", "R-Dynamic HSE"],
  "Land Rover|Defender": ["S", "SE", "HSE", "X-Dynamic S", "X-Dynamic SE", "X"],
  "Land Rover|Discovery": ["S", "SE", "HSE", "R-Dynamic SE", "R-Dynamic HSE"],
  "Land Rover|Discovery Sport": ["S", "SE", "R-Dynamic SE", "R-Dynamic HSE"],
  // Porsche
  "Porsche|911": ["Carrera", "Carrera S", "Carrera 4", "Carrera 4S", "Targa 4", "Targa 4S", "Turbo", "Turbo S", "GT3", "GT3 RS"],
  "Porsche|Cayenne": ["Base", "S", "GTS", "Turbo", "Turbo GT", "E-Hybrid"],
  "Porsche|Macan": ["Base", "S", "GTS", "Turbo", "Electric"],
  "Porsche|Panamera": ["Base", "4", "4S", "GTS", "Turbo", "Turbo S"],
  "Porsche|Taycan": ["Base", "4S", "GTS", "Turbo", "Turbo S", "Sport Turismo"],
  "Porsche|718 Boxster": ["Base", "S", "GTS", "Spyder", "GT4"],
  "Porsche|718 Cayman": ["Base", "S", "GTS", "GT4", "GT4 RS"],
  // Volvo
  "Volvo|XC40": ["Core", "Plus", "Ultra", "Plus Dark", "Ultra Dark", "Recharge"],
  "Volvo|XC60": ["Core", "Plus", "Ultra", "Plus Dark", "Ultra Dark", "Recharge"],
  "Volvo|XC90": ["Core", "Plus", "Ultra", "Plus Dark", "Ultra Dark", "Recharge"],
  "Volvo|V60": ["Core", "Plus", "Ultra", "Cross Country"],
  "Volvo|V90": ["Core", "Plus", "Ultra", "Cross Country"],
  "Volvo|S60": ["Core", "Plus", "Ultra"],
  "Volvo|S90": ["Core", "Plus", "Ultra", "Recharge"],
  "Volvo|C40": ["Core", "Plus", "Ultra"],
  // MG
  "MG|ZS": ["Comfort", "Luxury", "Trophy", "EV"],
  "MG|4": ["Comfort", "Luxury", "Trophy", "XPOWER"],
  "MG|HS": ["Comfort", "Luxury", "Trophy", "Plug-in Hybrid"],
  "MG|5": ["Comfort", "Luxury", "Trophy"],
  // Subaru
  "Subaru|Forester": ["Trending", "Premium", "Sport", "Limited"],
  "Subaru|Outback": ["Trending", "Premium", "Sport", "Limited"],
  "Subaru|XV": ["Trending", "Premium", "Sport", "Limited"],
  "Subaru|Impreza": ["1.6i", "2.0i", "Sport"],
  "Subaru|WRX": ["WRX", "STI", "STI S"],
  "Subaru|BRZ": ["Base", "Sport", "GT"],
  // Suzuki
  "Suzuki|Swift": ["GL+", "Avantage", "Pack", "Privilège", "Sport"],
  "Suzuki|Vitara": ["GL+", "Avantage", "Pack", "Privilège", "Allgrip"],
  "Suzuki|Jimny": ["Advance", "Style", "Style Leather"],
  "Suzuki|S-Cross": ["GL+", "Avantage", "Pack", "Privilège", "AllGrip"],
  "Suzuki|Ignis": ["GL+", "Avantage", "Pack", "Privilège"],
  "Suzuki|Baleno": ["GL+", "Avantage", "Pack"],
  // Mitsubishi
  "Mitsubishi|Outlander": ["Inform", "Instyle", "Diamond", "PHEV"],
  "Mitsubishi|ASX": ["Inform", "Instyle", "Diamond", "Intense"],
  "Mitsubishi|Eclipse Cross": ["Inform", "Instyle", "Diamond", "PHEV"],
  "Mitsubishi|Space Star": ["Base", "Intense"],
  "Mitsubishi|L200": ["Base", "Invite", "Intense", "Instyle"],
  // Lexus
  "Lexus|UX": ["Business", "Business Premium", "Luxury", "F Sport"],
  "Lexus|NX": ["Business", "Business Premium", "Luxury", "F Sport", "Plug-in"],
  "Lexus|RX": ["Business", "Business Premium", "Luxury", "F Sport", "Plug-in"],
  "Lexus|LBX": ["Comfort", "Cool", "Relax", "F Sport"],
  "Lexus|IS": ["Business", "Business Premium", "Luxury", "F Sport"],
  "Lexus|ES": ["Business", "Business Premium", "Luxury", "F Sport"],
  "Lexus|LC": ["Base", "Cabriolet", "500h"],
  // Jaguar
  "Jaguar|F-Pace": ["S", "SE", "HSE", "R-Dynamic S", "R-Dynamic SE", "R-Dynamic HSE", "SVR"],
  "Jaguar|E-Pace": ["S", "SE", "HSE", "R-Dynamic S", "R-Dynamic SE"],
  "Jaguar|I-Pace": ["S", "SE", "HSE", "EV400", "EV400 HSE"],
  "Jaguar|XE": ["S", "SE", "HSE", "R-Dynamic S", "R-Dynamic SE"],
  "Jaguar|XF": ["S", "SE", "HSE", "R-Dynamic SE", "R-Dynamic HSE"],
  "Jaguar|F-Type": ["Coupe", "Cabriolet", "R", "R-Dynamic"],
  // Maserati
  "Maserati|Ghibli": ["GT", "Modena", "Trofeo"],
  "Maserati|Levante": ["GT", "Modena", "Trofeo"],
  "Maserati|Quattroporte": ["GT", "Modena", "Trofeo"],
  "Maserati|GranTurismo": ["Modena", "Trofeo", "Folgore"],
  "Maserati|Grecale": ["GT", "Modena", "Trofeo", "Folgore"],
  // Genesis
  "Genesis|G70": ["Sport", "Prestige", "Elite"],
  "Genesis|G80": ["Sport", "Prestige", "Elite"],
  "Genesis|G90": ["Premium", "Prestige"],
  "Genesis|GV60": ["Sport", "Sport Plus", "Prestige"],
  "Genesis|GV70": ["Sport", "Prestige", "Elite"],
  "Genesis|GV80": ["Sport", "Prestige", "Elite"],
  // Polestar
  "Polestar|2": ["Standard Range", "Long Range Single Motor", "Long Range Dual Motor", "Performance"],
  "Polestar|3": ["Long Range Single Motor", "Long Range Dual Motor", "Performance"],
  "Polestar|4": ["Long Range Single Motor", "Long Range Dual Motor", "Performance"],
  // BYD
  "BYD|Atto 3": ["Design Edition", "Comfort", "Excellence"],
  "BYD|Seal": ["Design Edition", "Excellence"],
  "BYD|Dolphin": ["Active", "Comfort", "Design Edition"],
  "BYD|Han": ["Design Edition", "Excellence"],
  "BYD|Tang": ["Design Edition", "Excellence"],
  // Infiniti
  "Infiniti|Q50": ["Luxe", "Red Sport 400"],
  "Infiniti|Q60": ["Luxe", "Red Sport 400"],
  "Infiniti|QX50": ["Essential", "Luxe", "Sensory", "Autograph"],
  "Infiniti|QX60": ["Pure", "Luxe", "Sensory", "Autograph"],
  "Infiniti|QX80": ["Luxe", "Sensory", "Autograph"],
  // Rolls-Royce
  "Rolls-Royce|Ghost": ["Standard", "Extended", "Black Badge"],
  "Rolls-Royce|Phantom": ["Standard", "Extended", "Drophead Coupé"],
  "Rolls-Royce|Cullinan": ["Standard", "Black Badge"],
  "Rolls-Royce|Wraith": ["Standard", "Black Badge"],
  "Rolls-Royce|Dawn": ["Standard", "Black Badge"],
  "Rolls-Royce|Spectre": ["Standard", "Black Badge"],
  // Smart
  "Smart|#1": ["Pro", "Premium", "Brabus"],
  "Smart|#3": ["Pro", "Premium", "Brabus"],
  "Smart|EQ fortwo": ["Pure", "Passion", "Prime", "Brabus"],
  "Smart|EQ forfour": ["Pure", "Passion", "Prime", "Brabus"],
  // Aston Martin
  "Aston Martin|Vantage": ["Standard", "F1 Edition", "AMR"],
  "Aston Martin|DB11": ["V8", "V12", "AMR"],
  "Aston Martin|DB12": ["Standard", "Volante"],
  "Aston Martin|DBS Superleggera": ["Standard", "Superleggera", "Concorde Edition"],
  "Aston Martin|DBX": ["Standard", "DBX707"],
  "Aston Martin|Rapide": ["Base", "S", "AMR"],
  // Land Rover
  "Land Rover|Freelander": ["S", "SE", "HSE"],
  // Lexus
  "Lexus|CT": ["Base", "Luxury", "F Sport", "Executive"],
  "Lexus|LS": ["Base", "Luxury", "F Sport"],
  "Lexus|LX": ["Base", "Luxury", "F Sport"],
  // Subaru
  "Subaru|Levorg": ["Trending", "Premium", "Sport"],
  // Suzuki
  "Suzuki|Celerio": ["GL+", "Avantage"],
  "Suzuki|Swace": ["GL+", "Avantage", "Pack"],
  // Maserati
  "Maserati|MC20": ["Base", "Cielo"],
  // Polestar
  "Polestar|1": ["Base"],
  // BYD
  "BYD|Atto 2": ["Design Edition", "Comfort", "Excellence"],
  "BYD|Sealion 6": ["Design Edition", "Excellence"],
  // Smart
  "Smart|fortwo": ["Pure", "Passion", "Prime"],
};

export function getFinitionsForModele(marque: string, modele: string): string[] {
  return FINITIONS_PAR_MODELE[`${marque}|${modele}`] ?? [];
}

export const CARBURANTS = [
  { value: "essence", label: "Essence" },
  { value: "diesel", label: "Diesel" },
  { value: "hybride", label: "Hybride" },
  { value: "electrique", label: "Électrique" },
  { value: "gpl", label: "GPL" },
];

export const PUISSANCES_FISCALES = Array.from({ length: 20 }, (_, i) => ({
  value: String(i + 1),
  label: `${i + 1} CV${i + 1 === 20 ? "+" : ""}`,
}));

export const KILOMETRAGES = [
  { value: "lt5000", label: "Moins de 5 000 km" },
  { value: "5000-10000", label: "5 000 – 10 000 km" },
  { value: "10000-15000", label: "10 000 – 15 000 km" },
  { value: "15000-20000", label: "15 000 – 20 000 km" },
  { value: "gt20000", label: "Plus de 20 000 km" },
];

export const ASSUREURS_FR = [
  "Axa", "Allianz", "Groupama", "MAIF", "Macif", "GMF", "MMA", "Generali",
  "Matmut", "Maaf", "Direct Assurance", "Amaguiz", "Luko", "Lovys",
  "Netvox", "L'olivier Assurance", "Solly Azar", "Covéa",
  "Thélem Assurances", "April", "Assurland", "Autre",
].sort();

export const DEPARTEMENTS_COEFFICIENTS: Record<string, number> = {
  "75": 1.35, "92": 1.30, "93": 1.40, "94": 1.30,
  "69": 1.20, "13": 1.25, "31": 1.10, "33": 1.10,
  "59": 1.15, "67": 1.05, "06": 1.20, "44": 1.05,
  "default": 1.00,
};

export function getDepartementFromCodePostal(cp: string): string {
  const code = cp.substring(0, 2);
  if (cp.startsWith("97")) return cp.substring(0, 3);
  return code;
}
